// Firestore collection IDs and labels for View Records
export const COLLECTIONS = [
  { id: 'animalFeed', label: 'Animal Feeds Unit' },
  { id: 'animalWelfare', label: 'Animal Welfare' },
  { id: 'livestockHandlers', label: 'Livestock/Poultry/By-Products Handlers' },
  { id: 'transportCarrier', label: 'Transport Carriers' },
  { id: 'plantMaterial', label: 'Plant Material / Nursery' },
  { id: 'organicAgri', label: 'Organic Agriculture Certification' },
  { id: 'goodAgriPractices', label: 'Good Agricultural Practices' },
  { id: 'goodAnimalHusbandry', label: 'Good Animal Husbandry' },
  { id: 'organicPostMarket', label: 'Organic Post-Market Surveillance' },
  { id: 'landUseMatter', label: 'Land Use Matter' },
  { id: 'foodSafety', label: 'Food Safety' },
  { id: 'plantPestSurveillance', label: 'Plant Pest Surveillance' },
  { id: 'cfsAdmcc', label: 'CFS/ADMCC' },
  { id: 'animalDiseaseSurveillance', label: 'Animal Disease Surveillance' },
]

// For table display: which field to show as primary name per collection
export const COLLECTION_TITLE_FIELD = {
  animalFeed: 'companyName',
  animalWelfare: 'facilityName',
  livestockHandlers: 'ownershipType',
  transportCarrier: 'ownerName',
  plantMaterial: 'nurseryName',
  organicAgri: 'entityName',
  goodAgriPractices: 'farmName',
  goodAnimalHusbandry: 'farmName',
  organicPostMarket: 'establishmentName',
  landUseMatter: 'landowner',
  foodSafety: 'nameOfEstablishment',
  plantPestSurveillance: 'farmerName',
  cfsAdmcc: 'establishment',
  animalDiseaseSurveillance: 'farmOwnerName',
}

// Edit modal: same order as in each form (do not change order)
export const COLLECTION_FIELD_ORDER = {
  animalFeed: ['date', 'province', 'controlNo', 'registrationNo', 'dateOfInspection', 'dateOfMonitoring', 'companyName', 'lastName', 'middleName', 'firstName', 'nameExt', 'completeName', 'birthDate', 'barangay', 'municipality', 'completeAddress', 'officeAddress', 'plantAddress', 'cellphone', 'email', 'natureOfBusiness', 'businessOrg', 'productLines', 'type', 'orNo', 'orDate', 'fee', 'dateIssued', 'dateOfFeedSampling1stSem', 'dateOfFeedSampling2ndSem', 'noOfFeedSamples1stSem', 'noOfFeedSamples2ndSem', 'attachmentFileName', 'attachmentData', 'remarks'],
  animalWelfare: ['dateApplied', 'facilityName', 'ownerName', 'address', 'facilityType', 'speciesHandled', 'headVet', 'prcLicenseNo', 'certificateNo', 'validityDate', 'status'],
  livestockHandlers: ['ownershipType', 'singleName', 'companyName', 'repName', 'address', 'businessType', 'contact', 'applicantType', 'category', 'livestock', 'poultry', 'byProducts', 'region'],
  transportCarrier: ['ownerName', 'businessAddress', 'businessOrg', 'typeOfApplicant', 'contactNo', 'email', 'applicantTin', 'companyTin', 'typeOfServices', 'applicationType', 'speciesCargoBirds', 'speciesAnimals', 'byProducts', 'typeOfVehicle', 'bodyType', 'fleet'],
  plantMaterial: ['dateApplied', 'nurseryName', 'operatorName', 'farmLocation', 'totalArea', 'plantMaterials', 'specificVariety', 'propagatorName', 'accreditationNo', 'validityDate', 'remarks'],
  organicAgri: ['dateApplied', 'entityName', 'operatorOwner', 'location', 'scope', 'certifyingBody', 'commodities', 'conversionStartDate', 'certificationStatus', 'certificateNo', 'validityDate'],
  goodAgriPractices: ['applicationDate', 'farmName', 'farmOwner', 'farmLocation', 'cropsPlanted', 'productionArea', 'harvestEstimate', 'waterSource', 'philgapCertNo', 'dateIssued', 'expiryDate'],
  goodAnimalHusbandry: ['applicationDate', 'farmName', 'owner', 'farmAddress', 'farmType', 'population', 'biosecurityLevel', 'eccNo', 'gahpCertNo', 'validity', 'inspectionStatus'],
  organicPostMarket: ['inspectionDate', 'establishmentName', 'address', 'productName', 'brand', 'labelClaim', 'certifyingLogoPresent', 'violationFound', 'actionTaken', 'inspectorName'],
  landUseMatter: ['dateReceived', 'landowner', 'lotTitleNo', 'location', 'totalLandArea', 'existingCropUsage', 'proposedUsage', 'safdzZone', 'daClearanceNo', 'status'],
  foodSafety: ['dateOfMonitoring', 'establishmentType', 'nameOfEstablishment', 'address', 'productInspected', 'batchLotNo', 'sensoryAnalysis', 'labSampleCollected', 'labResult', 'remarks'],
  plantPestSurveillance: ['dateOfMonitoring', 'location', 'farmerName', 'cropAffected', 'stageOfCrop', 'pestDiseaseObserved', 'incidenceRate', 'damageSeverity', 'actionTaken', 'technicianName'],
  cfsAdmcc: ['date', 'establishment', 'sampleType', 'parameterTested', 'sourceOrigin', 'resultValue', 'standardLimit', 'compliance', 'referenceReportNo'],
  animalDiseaseSurveillance: ['dateReported', 'barangay', 'municipality', 'farmOwnerName', 'species', 'clinicalSigns', 'totalPopulation', 'mortality', 'laboratoryTest', 'result', 'controlMeasures'],
}

// Same labels as in Animal Feed form (for Edit Record in View Records)
export const COLLECTION_FIELD_LABELS = {
  animalFeed: {
    date: 'Date of Application/Valuated',
    province: 'Province',
    controlNo: 'Control No.',
    registrationNo: 'Registration No.',
    dateOfInspection: 'Date of Inspection',
    dateOfMonitoring: 'Date of Monitoring',
    companyName: 'Name of Establishment',
    lastName: 'Last Name',
    middleName: 'Middle Name',
    firstName: 'First Name',
    nameExt: 'Name Ext.',
    completeName: 'Complete Name',
    birthDate: 'Birth Date',
    barangay: 'Barangay',
    municipality: 'Municipality',
    completeAddress: 'Complete Address',
    officeAddress: 'Office Address',
    plantAddress: 'Plant/Warehouse Address',
    cellphone: 'Contact No.',
    email: 'Email Address',
    natureOfBusiness: 'Nature of Business',
    businessOrg: 'Business Organization',
    productLines: 'Product Line',
    type: 'Type',
    orNo: 'Official Receipt No.',
    orDate: 'Official Receipt Date',
    fee: 'Fees Collected',
    dateIssued: 'Date of Issuance of LTO',
    dateOfFeedSampling1stSem: 'Date of Feed Sampling (1st Semester)',
    dateOfFeedSampling2ndSem: 'Date of Feed Sampling (2nd Semester)',
    noOfFeedSamples1stSem: 'No. of Feed Samples Collected (1st Semester)',
    noOfFeedSamples2ndSem: 'No. of Feed Samples Collected (2nd Semester)',
    attachmentFileName: 'Attachments (file name)',
    attachmentData: 'Attachments (file)',
    remarks: 'Remarks',
  },
}
