// Firestore collection IDs and labels for View Records

/** Form path (e.g. /dashboard/forms/animal-feed) to collection id (e.g. animalFeed) */
export function pathToCollectionId(path) {
  const slug = (path || '').split('/').pop() || ''
  return slug.split('-').map((s, i) => (i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1))).join('')
}

// Collection IDs that have a form in pages/forms — Edit in ViewRecords uses COLLECTION_FIELD_ORDER & COLLECTION_FIELD_LABELS below so each form’s fields are what you see/edit.
export const FORM_COLLECTION_IDS = [
  'animalFeed',
  'animalWelfare',
  'livestockHandlers',
  'transportCarrier',
  'plantMaterial',
  'organicAgri',
  'goodAgriPractices',
  'goodAnimalHusbandry',
  'organicPostMarket',
  'landUseMatter',
  'foodSafety',
  'plantPestSurveillance',
  'cfsAdmcc',
  'animalDiseaseSurveillance',
  'safdzValidation',
]

export const COLLECTIONS = [
  { id: 'animalFeed', label: 'Animal Feeds Unit' },
  { id: 'animalWelfare', label: 'Animal Welfare' },
  { id: 'livestockHandlers', label: 'Livestock/Poultry/By-Products Handlers' },
  { id: 'transportCarrier', label: 'Transport Carriers' },
  { id: 'plantMaterial', label: 'Plant Material / Nursery' },
  { id: 'organicAgri', label: 'Organic Agriculture Certification' },
  { id: 'goodAgriPractices', label: 'Good Agricultural Practices' },
  { id: 'goodAnimalHusbandry', label: 'Good Animal Husbandry' },
  { id: 'organicPostMarket', label: 'Organic Post-Market Surveillance' },
  { id: 'landUseMatter', label: 'Land Use Matter' },
  { id: 'foodSafety', label: 'Food Safety' },
  { id: 'plantPestSurveillance', label: 'Plant Pest Surveillance' },
  { id: 'cfsAdmcc', label: 'CFS/ADMCC' },
  { id: 'animalDiseaseSurveillance', label: 'Animal Disease Surveillance' },
  { id: 'safdzValidation', label: 'SAFDZ Validation' },
]

// For table display: which field to show as primary name per collection
export const COLLECTION_TITLE_FIELD = {
  animalFeed: 'companyName',
  animalWelfare: 'facilityName',
  livestockHandlers: 'nameOfEstablishment',
  transportCarrier: 'nameOfEstablishment',
  plantMaterial: 'applicant',
  organicAgri: 'nameOfApplicant',
  goodAgriPractices: 'nameOfApplicant',
  goodAnimalHusbandry: 'recommendation',
  organicPostMarket: 'identifiedMarketOutlet',
  landUseMatter: 'nameOfApplicant',
  foodSafety: 'recommendation',
  plantPestSurveillance: 'farmerName',
  cfsAdmcc: 'clientName',
  animalDiseaseSurveillance: 'clientName',
  safdzValidation: 'nameOfApplicant',
}

// Edit modal in ViewRecords: same order as in each form in pages/forms (keep in sync with form payloads).
export const COLLECTION_FIELD_ORDER = {
  animalFeed: ['date', 'province', 'controlNo', 'registrationNo', 'dateOfInspection', 'dateOfMonitoring', 'companyName', 'lastName', 'middleName', 'firstName', 'nameExt', 'completeName', 'birthDate', 'barangay', 'municipality', 'completeAddress', 'officeAddress', 'plantAddress', 'cellphone', 'email', 'natureOfBusiness', 'businessOrg', 'productLines', 'type', 'orNo', 'orDate', 'fee', 'dateIssued', 'dateOfFeedSampling1stSem', 'dateOfFeedSampling2ndSem', 'noOfFeedSamples1stSem', 'noOfFeedSamples2ndSem', 'attachmentFileName', 'attachmentData', 'remarks', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  animalWelfare: ['dateApplied', 'facilityName', 'ownerName', 'province', 'address', 'facilityType', 'certificateNo', 'dateOfInspection', 'orNo', 'orDate', 'fee', 'endorsementToBAI', 'registrationDate', 'validityDate', 'status', 'applicationType', 'speciesHandled', 'headVet', 'prcLicenseNo', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  livestockHandlers: ['controlNo', 'registrationNo', 'nameOfEstablishment', 'nameOfApplicant', 'address', 'province', 'typeOfApplication', 'dateOfApplicationReceivedAndEvaluated', 'orNumber', 'orDate', 'amountOfFeeCollected', 'dateOfInspection', 'dateOfCertification', 'transmittalDateToBAI', 'validity', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  transportCarrier: ['controlNo', 'registrationNo', 'nameOfEstablishment', 'nameOfApplicant', 'address', 'province', 'typeOfApplication', 'dateOfApplicationReceivedAndEvaluated', 'orNumber', 'orDate', 'amountOfFeeCollected', 'dateOfInspectionAndMonitoring', 'dateOfCertification', 'transmittalDateToBAI', 'validity', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  plantMaterial: ['applicant', 'operator', 'province', 'location', 'cropsVariety', 'submissionOfApplicationForm', 'evaluationOfDocumentary', 'paymentOfApplicationFee', 'amountOfFee', 'dateOfInspectionAndEvaluation', 'approvedValidatedResult', 'endorsementToBPI', 'dateOfInspection1stSem', 'dateOfInspection2ndSem', 'status', 'validity', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  organicAgri: ['application', 'nameOfGroup', 'nameOfApplicant', 'province', 'location', 'area', 'dateOfEvaluation', 'remarks', 'dateOfEndorsement', 'finalInspection', 'status', 'issuanceOfCertificate', 'finalRemarks', 'linkFile', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  goodAgriPractices: ['formType', 'controlNo', 'dateOfRequest', 'nameOfApplicant', 'location', 'province', 'area', 'crop', 'dateOfPreAssessment', 'remarks', 'dateOfEndorsementToBPI', 'dateOfFinalInspection', 'status', 'dateOfMonitoring', 'nameOfFarmer', 'certificateNumber', 'certificateValidity', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  goodAnimalHusbandry: ['province', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  organicPostMarket: ['requestLetterDate', 'identifiedMarketOutlet', 'dateOfCommunicationLetter', 'nameOfProduct', 'commodity', 'certification', 'nameOfOwnerManager', 'province', 'location', 'dateOfSurveillance', 'remarks', 'linkFile', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  landUseMatter: ['controlNo', 'nameOfApplicant', 'purposeOfApplication', 'sizeOfArea', 'province', 'location', 'dateOfRequest', 'dateReceivedAndEvaluated', 'dateOfReplyToRequest', 'dateReceivedByApplicant', 'fieldInvestigation', 'dateOfEndorsement', 'issuanceOfCertificate', 'remarks', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  foodSafety: ['province', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  plantPestSurveillance: ['dateOfRequestAndCollection', 'farmerName', 'province', 'address', 'contactNumber', 'gpsLocation', 'crop', 'variety', 'datePlanted', 'areaPlanted', 'areaAffected', 'percentInfestation', 'pestsDiseases', 'remarks', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  cfsAdmcc: ['clientName', 'typeOfDiseaseSurveillance', 'purpose', 'province', 'address', 'dateOfRequest', 'dateOfSurveillance', 'numberOfSamples', 'dateSubmittedToLab', 'dateOfEndorsementToDA', 'remarks', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  animalDiseaseSurveillance: ['clientName', 'typeOfDiseaseSurveillance', 'purpose', 'province', 'address', 'dateOfRequest', 'dateOfSurveillance', 'numberOfSamples', 'dateSubmittedToLab', 'dateOfEndorsementToDA', 'remarks', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  safdzValidation: ['explorationPermitApplicationNo', 'nameOfApplicant', 'dateReceived', 'province', 'location', 'area', 'dateOfReplyToRequest', 'endorsementToBSWM', 'endorsementToMGB', 'fieldValidation', 'remarks', 'rescheduledDate', 'fieldValidationReport', 'issuanceOfCertificateAndEndorsementToMGB', 'status', 'findings', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
}

// GoodAgriPractices: which fields to show in ViewRecords Edit per form type (only that form’s fields)
export const GOOD_AGRI_PRACTICES_FORM_FIELDS = {
  gapCertification: ['formType', 'controlNo', 'dateOfRequest', 'nameOfApplicant', 'location', 'province', 'area', 'crop', 'dateOfPreAssessment', 'remarks', 'dateOfEndorsementToBPI', 'dateOfFinalInspection', 'status', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
  monitoring: ['formType', 'controlNo', 'dateOfMonitoring', 'nameOfFarmer', 'location', 'province', 'area', 'certificateNumber', 'certificateValidity', 'remarks', 'ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness', 'recommendation'],
}

// Rating fields for Plant Pest Surveillance (1-5 scale)
export const PLANT_PEST_RATING_FIELDS = ['ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness']
// Rating fields for CFS/ADMCC (same structure)
export const CFSADMCC_RATING_FIELDS = ['ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness']
// Rating fields for Animal Disease Surveillance (same structure)
export const ANIMAL_DISEASE_RATING_FIELDS = ['ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness']
// Rating fields for Plant Material / Nursery (same structure)
export const PLANT_MATERIAL_RATING_FIELDS = ['ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness']
// Rating fields for Organic Agriculture Certification (same structure)
export const ORGANIC_AGRI_RATING_FIELDS = ['ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness']
// Shared rating fields (all collections use same structure)
export const RATING_FIELD_KEYS = ['ratingQuantity', 'ratingServicesPersonnel', 'ratingTraining', 'ratingAttitude', 'ratingPromptness']
export const RATING_LABELS = { '1': 'Poor', '2': 'Fair', '3': 'Satisfied', '4': 'Very Satisfied', '5': 'Excellent' }

// Same labels as in Animal Feed form (for Edit Record in View Records)
export const COLLECTION_FIELD_LABELS = {
  animalFeed: {
    date: 'Date of Application/Valuated',
    province: 'Province',
    controlNo: 'Control No.',
    registrationNo: 'Registration No.',
    dateOfInspection: 'Date of Inspection',
    dateOfMonitoring: 'Date of Monitoring',
    companyName: 'Name of Establishment',
    lastName: 'Last Name',
    middleName: 'Middle Name',
    firstName: 'First Name',
    nameExt: 'Name Ext.',
    completeName: 'Complete Name',
    birthDate: 'Birth Date',
    barangay: 'Barangay',
    municipality: 'Municipality',
    completeAddress: 'Complete Address',
    officeAddress: 'Office Address',
    plantAddress: 'Plant/Warehouse Address',
    cellphone: 'Contact No.',
    email: 'Email Address',
    natureOfBusiness: 'Nature of Business',
    businessOrg: 'Business Organization',
    productLines: 'Product Line',
    type: 'Type',
    orNo: 'Official Receipt No.',
    orDate: 'Official Receipt Date',
    fee: 'Fees Collected',
    dateIssued: 'Date of Issuance of LTO',
    dateOfFeedSampling1stSem: 'Date of Feed Sampling (1st Semester)',
    dateOfFeedSampling2ndSem: 'Date of Feed Sampling (2nd Semester)',
    noOfFeedSamples1stSem: 'No. of Feed Samples Collected (1st Semester)',
    noOfFeedSamples2ndSem: 'No. of Feed Samples Collected (2nd Semester)',
    attachmentFileName: 'Attachments (file name)',
    attachmentData: 'Attachments (file)',
    remarks: 'Remarks',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  animalWelfare: {
    dateApplied: 'Date of Application',
    facilityName: 'Facility Name (Business Name)',
    ownerName: 'Owner / Operator Name',
    province: 'Province',
    address: 'Complete Address',
    facilityType: 'Facility Type',
    certificateNo: 'Registration No.',
    dateOfInspection: 'Date of Inspection',
    orNo: 'OR Number',
    orDate: 'OR Date',
    fee: 'Amount of Fee Collected',
    endorsementToBAI: 'Endorsement to BAI',
    registrationDate: 'Registration Date',
    validityDate: 'Validity Date',
    status: 'Current Status',
    applicationType: 'New / Renewal',
    speciesHandled: 'Species Handled',
    headVet: 'Head Veterinarian',
    prcLicenseNo: 'PRC License No.',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  livestockHandlers: {
    controlNo: 'No.',
    registrationNo: 'Registration No.',
    nameOfEstablishment: 'Name of Establishment',
    nameOfApplicant: 'Name of Applicant',
    address: 'Address',
    province: 'Province',
    typeOfApplication: 'Type of Application',
    dateOfApplicationReceivedAndEvaluated: 'Date of Application Received & Evaluated',
    orNumber: 'OR Number',
    orDate: 'OR Date',
    amountOfFeeCollected: 'Amount of Fee Collected',
    dateOfInspection: 'Date of Inspection',
    dateOfCertification: 'Date of Certification',
    transmittalDateToBAI: 'Transmittal Date to BAI',
    validity: 'Validity',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  transportCarrier: {
    controlNo: 'No.',
    registrationNo: 'Registration No.',
    nameOfEstablishment: 'Name of Establishment',
    nameOfApplicant: 'Name of Applicant',
    address: 'Address',
    province: 'Province',
    typeOfApplication: 'Type of Application',
    dateOfApplicationReceivedAndEvaluated: 'Date of Application Received & Evaluated',
    orNumber: 'OR Number',
    orDate: 'OR Date',
    amountOfFeeCollected: 'Amount of Fee Collected',
    dateOfInspectionAndMonitoring: 'Date of Inspection and Monitoring',
    dateOfCertification: 'Date of Certification',
    transmittalDateToBAI: 'Transmittal Date to BAI',
    validity: 'Validity',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  plantMaterial: {
    applicant: 'Applicant',
    operator: 'Operator',
    province: 'Province',
    location: 'Location',
    cropsVariety: 'Crops/Variety',
    submissionOfApplicationForm: "Submission of Client's Filled Application Form to DA-Regulatory Division",
    evaluationOfDocumentary: 'Evaluation of Submitted Documentary Requirements',
    paymentOfApplicationFee: 'Payment of Application Fee',
    amountOfFee: 'Amount of Fee',
    dateOfInspectionAndEvaluation: 'Date of Inspection and Evaluation of Nursery',
    approvedValidatedResult: 'Approved Validated Result of Inspection and Validation of Areas',
    endorsementToBPI: 'Endorsement of Application to BPI',
    dateOfInspection1stSem: 'Date of Inspection and Monitoring (1st Semester)',
    dateOfInspection2ndSem: 'Date of Inspection and Monitoring (2nd Semester)',
    status: 'Status',
    validity: 'Validity',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  organicPostMarket: {
    requestLetterDate: 'Request Letter (Date)',
    identifiedMarketOutlet: 'Identified Market Outlet/Establishment',
    dateOfCommunicationLetter: 'Date of Communication Letter',
    nameOfProduct: 'Name of Product',
    commodity: 'Commodity',
    certification: 'Certification',
    nameOfOwnerManager: 'Name of Owner/Manager',
    province: 'Province',
    location: 'Location',
    dateOfSurveillance: 'Date of Surveillance',
    remarks: 'Remarks',
    linkFile: 'Link File',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  landUseMatter: {
    controlNo: 'Control No.',
    nameOfApplicant: 'Name of Applicant',
    purposeOfApplication: 'Purpose of Application',
    sizeOfArea: 'Size of Area (ha)',
    province: 'Province',
    location: 'Location',
    dateOfRequest: 'Date of Request',
    dateReceivedAndEvaluated: 'Date Received and Evaluated',
    dateOfReplyToRequest: 'Date of Reply to the Request',
    dateReceivedByApplicant: 'Date Received by the Applicant',
    fieldInvestigation: 'Field Investigation',
    dateOfEndorsement: 'Date of Endorsement',
    issuanceOfCertificate: 'Issuance of Certificate',
    remarks: 'Remarks',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  organicAgri: {
    application: 'Application',
    nameOfGroup: 'Name of Group',
    nameOfApplicant: 'Name of Applicant',
    province: 'Province',
    location: 'Location',
    area: 'Area',
    dateOfEvaluation: 'Date of Evaluation',
    remarks: 'Remarks',
    dateOfEndorsement: 'Date of Endorsement',
    finalInspection: 'Final Inspection',
    status: 'Status',
    issuanceOfCertificate: 'Issuance of Certificate',
    finalRemarks: 'Remarks',
    linkFile: 'Link File',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  goodAgriPractices: {
    formType: 'Form Type',
    controlNo: 'No.',
    dateOfRequest: 'Date of Request',
    nameOfApplicant: 'Name of Applicant',
    location: 'Location',
    province: 'Province',
    area: 'Area (ha)',
    crop: 'Crop',
    dateOfPreAssessment: 'Date of Pre-assessment',
    remarks: 'Remarks',
    dateOfEndorsementToBPI: 'Date of Endorsement to BPI',
    dateOfFinalInspection: 'Date of Final Inspection',
    status: 'Status',
    dateOfMonitoring: 'Date of Monitoring',
    nameOfFarmer: 'Name of Farmer',
    certificateNumber: 'Certificate Number',
    certificateValidity: 'Certificate Validity',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  goodAnimalHusbandry: {
    province: 'Province',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  plantPestSurveillance: {
    dateOfRequestAndCollection: 'Date of Request and Collection',
    farmerName: 'Name of Farmer',
    province: 'Province',
    address: 'Address',
    contactNumber: 'Contact Number',
    gpsLocation: 'GPS Location',
    crop: 'Crop',
    variety: 'Variety',
    datePlanted: 'Date Planted',
    areaPlanted: 'Area Planted (ha)',
    areaAffected: 'Area Affected',
    percentInfestation: 'Percent Infestation',
    pestsDiseases: 'Pests/Diseases',
    remarks: 'Remarks',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  cfsAdmcc: {
    clientName: 'Name of Local Government Unit/Client/Farm',
    typeOfDiseaseSurveillance: 'Type of Disease Surveillance',
    purpose: 'Purpose',
    province: 'Province',
    address: 'Address',
    dateOfRequest: 'Date of Request',
    dateOfSurveillance: 'Date of Surveillance (Blood Collection)',
    numberOfSamples: 'Number of Samples Collected & Submitted',
    dateSubmittedToLab: 'Date Submitted to Laboratory',
    dateOfEndorsementToDA: 'Date of Endorsement to DA-BAI',
    remarks: 'Remarks',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  animalDiseaseSurveillance: {
    clientName: 'Name of Local Government Unit/Client/Farm',
    typeOfDiseaseSurveillance: 'Type of Disease Surveillance',
    purpose: 'Purpose',
    province: 'Province',
    address: 'Address',
    dateOfRequest: 'Date of Request',
    dateOfSurveillance: 'Date of Surveillance (Blood Collection)',
    numberOfSamples: 'Number of Samples Collected & Submitted',
    dateSubmittedToLab: 'Date Submitted to Laboratory',
    dateOfEndorsementToDA: 'Date of Endorsement to DA-BAI',
    remarks: 'Remarks',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
  safdzValidation: {
    explorationPermitApplicationNo: 'Exploration Permit Application No.',
    nameOfApplicant: 'Name of Applicant',
    dateReceived: 'Date Received',
    province: 'Province',
    location: 'Location',
    area: 'Area (ha)',
    dateOfReplyToRequest: 'Date of Reply to the Request',
    endorsementToBSWM: 'Endorsement to BSWM',
    endorsementToMGB: 'Endorsement to MGB',
    fieldValidation: 'Field Validation',
    remarks: 'Remarks',
    rescheduledDate: 'Rescheduled date',
    fieldValidationReport: 'Field Validation Report',
    issuanceOfCertificateAndEndorsementToMGB: 'Issuance of Certificate and Endorsement to MGB',
    status: 'Status',
    findings: 'Findings',
    ratingQuantity: '1. Quantity of Goods/Services Provided',
    ratingServicesPersonnel: '2. Services Rendered by Personnel',
    ratingTraining: '2.1 For training consider its relevance',
    ratingAttitude: '2.2 Attitude (courteousness)',
    ratingPromptness: '2.3 Promptness in attending the request',
    recommendation: 'Recommendation',
  },
}
